embedding_save_location: "./npm1_variance"
orig_df: /allen/aics/assay-dev/users/Alex/replearn/rep_paper/data/var_npm1_manifest.csv
image_path: /allen/aics/assay-dev/users/Alex/replearn/rep_paper/data/var_npm1_manifest.csv
pc_path: /allen/aics/assay-dev/users/Alex/replearn/rep_paper/data/var_npm1_manifest.csv
run_ids: [
            "b88c7f31a44347ba918edce252337468",
            "14e969bbeb554e688dff56014f359192",
            "93942206dd55425e8adcdcbd4df18b00",
            "1d398530dd0349df8150af342b407dd4",
            "ee6b24c15a1e485f9862b6dd1aef94e5",
        ]
names: [
            "PC_equiv",
            "CNN_sdf_SO3",
            "CNN_seg_SO3",
            "CNN_sdf_noalign",
            "CNN_seg_noalign",
        ]
data_paths: [
        "../data/configs/inference_npm1_variance/pointcloud_sdf_noalign.yaml",
        "../data/configs/inference_npm1_variance/image_sdf_noalign_so3.yaml",
        "../data/configs/inference_npm1_variance/image_seg_noalign_so3.yaml",
        "../data/configs/inference_npm1_variance/image_sdf_noalign.yaml",
        "../data/configs/inference_npm1_variance/image_seg_noalign.yaml",
    ]