embedding_save_location: 
orig_df: 
image_path: 
pc_path: 
run_ids: [
            "aec9d28492a7402ebf335240531968a5",
            "b39653afa5d042a6a105df95d6fecb13",
            "2675e1d1f8904396a745d3757a2ad64f",
            "3a035fe44e234e6ebc2d0fa48e18c1a4",
            "c1f61ed4aea34e5abdb2d711b818cb28",
        ]
names: [
            "IAE_comb_SO3_ld512_AE_gridlossW2_PT",
            "CNN_sdf_SO3_PT",
            "CNN_seg_SO3_PT",
            "CNN_sdf_noalign_PT",
            "CNN_seg_noalign_PT",
        ]
data_paths: [
        "../data/configs/inference_npm1_perturb/pointcloud_sdf_noalign.yaml",
        "../data/configs/inference_npm1_perturb/image_sdf_noalign_so3.yaml",
        "../data/configs/inference_npm1_perturb/image_seg_noalign_so3.yaml",
        "../data/configs/inference_npm1_perturb/image_sdf_noalign.yaml",
        "../data/configs/inference_npm1_perturb/image_seg_noalign.yaml",
    ],