embedding_save_location: "./variance_punct_structnorm"
orig_df: /allen/aics/assay-dev/MicroscopyOtherData/Viana/projects/cvapipe_analysis/local_staging_variance/loaddata/manifest.csv
image_path: /allen/aics/modeling/ritvik/variance_punctate/manifest_all_punctate.parquet
pc_path: /allen/aics/modeling/ritvik/variance_punctate/manifest_all_punctate.parquet
run_ids: [
            "0fd3e79d8aba45cca21b74da182c93f5",
            # "41cf98f1381f4eb097166beee598f56d",
        ]
names: [
            "var_punct_structnorm"
        ]
data_paths: [
        "/allen/aics/modeling/ritvik/projects/cytodl-internal-configs/data/variance_all_punctate/punctate_int_updated_morepoints_structurenorm.yaml",
    ]