defaults:
  - pc_encoders@encoder.pcloud: equiv_scalar.yaml
  - pc_decoders@decoder.pcloud: foldingnet_scalar.yaml
  - priors@prior.pcloud: identity.yaml
  - reconstruction_loss@reconstruction_loss.pcloud: earthmovers.yaml

_target_: cyto_dl.models.vae.PointCloudVAE

x_label: pcloud
occupancy_label:

latent_dim: 256
scale: 1
num_output_points: 2048
hidden_conv1_dim: 512
cond_dim:

encoder:
  pcloud:
    num_features: ${eval:${model.latent_dim}*${model.scale}}
    hidden_conv1d_channels: [512, 256]

decoder:
  pcloud:
    input_dim: ${model.latent_dim}
    num_output_points: ${model.num_output_points}

prior:
  pcloud:
    dimensionality: ${model.latent_dim}

beta: 1.0

get_rotation: true

optimizer:
  _partial_: true
  _target_: torch.optim.adam.Adam
  lr: 0.0002
