defaults:
  - _base

step:
  _target_: image_preprocessing.steps.Merge
  raw_col: crop_raw
  seg_col: crop_seg
  channel_map_col: name_dict
  output_dir: ${output_dir}/merge
  n_workers: ${n_workers}
  manifest_path: ${input_manifest}
  seg_channel_subset: ["dna_segmentation"]

input: ${input_manifest}
