defaults:
  - _base

step:
  _target_: image_preprocessing.steps.Register
  input_col: aligned_image
  quantile: 0.95
  membrane_seg_channel: dna_segmentation
  output_dir: ${output_dir}/register

input: ${output_dir}/align/manifest.parquet
