_target_: cyto_dl.models.vae.ImageVAE
group: so3
latent_dim: 256
spatial_dims: 3
in_shape: [1, 118, 118, 118]
channels:
  - 8
  - 16
  - 32
  - 64
  - 128
  - 256
  - 512
strides:
  - 1
  - 1
  - 2
  - 2
  - 2
  - 2
  - 2
kernel_sizes:
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
encoder_padding:
  - null
  - null
  - null
  - null
  - null
  - null
  - null
first_conv_padding_mode: replicate
num_res_units: 1
decoder_channels:
  - 512
  - 256
  - 128
  - 64
  - 32
  - 16
decoder_strides:
  - 2
  - 2
  - 2
  - 2
  - 1
  - 1

background_value: 0

mask_input: false
mask_output: true

x_label: pcloud
id_label: null

act: relu
norm: batch
dropout: null
bias: true
beta: 0

reconstruction_loss:
  _target_: torch.nn.MSELoss
  reduction: mean

prior:
  _target_: cyto_dl.models.vae.priors.IdentityPrior
  dimensionality: 256

last_act: null
optimizer:
  _partial_: true
  _target_: torch.optim.adam.Adam
  lr: 0.001
