defaults:
  - _self_
  - step: _base

# n_workers: 120
n_workers: 10
verbose: true
force: false
raise_errors: true

output_dir: your_output_path_here

input_manifest: your_path_here

remote_provider:

output_root: /tmp/variance_preprocessing_workflow
hydra:
  run:
    dir: ${output_root}/${now:%Y-%m-%d}/${now:%H-%M-%S_%f}
  sweep:
    dir: ${output_root}/${now:%Y-%m-%d}
    subdir: ${now:%H-%M-%S_%f}
