defaults:
  - _self_
  - step: _base

# n_workers: 120
n_workers: 1
verbose: true
force: false
raise_errors: true
samples_per_structure:

output_dir: /allen/aics/modeling/ritvik/projects/latest_clones/benchmarking_representations/subpackages/image_preprocessing/tmp_pcna/

input_manifest: /allen/aics/modeling/ritvik/projects/pcna_test.csv

remote_provider:

output_root: /tmp/variance_preprocessing_workflow
hydra:
  run:
    dir: ${output_root}/${now:%Y-%m-%d}/${now:%H-%M-%S_%f}
  sweep:
    dir: ${output_root}/${now:%Y-%m-%d}
    subdir: ${now:%H-%M-%S_%f}
